name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  flutter_svg: ^2.2.3
  material_symbols_icons:
  smooth_page_indicator:
  flutter_hooks:
  url_launcher:
  auto_size_text:
  transparent_image:
  gif_view:
  video_player: 
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod:
  riverpod_annotation:
  hooks_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  build_runner:
  json_serializable:
  riverpod_generator:
  riverpod_lint:
  json_annotation: ^4.9.0

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/
  - assets/screens/
  - assets/icon/
  - assets/profile/